api/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from api.entm.users.views import UserViewSet

from django.conf.urls import url
from django.contrib import admin

from .views import (
    OrganizationListAPIView,
    OrganizationDetailAPIView,
    MyRoleListAPIView,
    UserListAPIView,
    SimCardListAPIView,
    MeterListAPIView,
    StationListAPIView,
    StationDetailAPIView,
    VConcentratorListAPIView,
    VCommunityListAPIView,
    VPressureListAPIView,
    VPressureDetailAPIView,
    VSecondwaterListAPIView,
    VWatermeterListAPIView,
    VWatermeterDetailAPIView,
    WaterUserTypeListAPIView,
    MetercommListAPIView,
    MeterParameterListAPIView,
    MeterprotocolListAPIView,
    PersonalizedListAPIView,
)



router = routers.DefaultRouter()
router.register(r'users', UserViewSet)

app_name='api'
urlpatterns = [
    url(r'^', include(router.urls)),
    # url(r'^auth/', include('rest_auth.urls')),

    url(r'^personlized/list/$', PersonalizedListAPIView.as_view(), name='personlized'),
    url(r'^organizations/list/$', OrganizationListAPIView.as_view(), name='organlist'),
    url(r'^organizations/list/(?P<pk>\d+)/$', OrganizationDetailAPIView.as_view(), name='detail'),
    url(r'^role/list/$', MyRoleListAPIView.as_view(), name='myrolelist'),
    url(r'^user/list/$', UserListAPIView.as_view(), name='userlist'),
    url(r'^simcard/list/$', SimCardListAPIView.as_view(), name='simcardlist'),
    url(r'^meter/list/$', MeterListAPIView.as_view(), name='meterlist'),
    url(r'^station/list/$', StationListAPIView.as_view(), name='stationlist'),
    url(r'^station/list/(?P<pk>\d+)/$', StationDetailAPIView.as_view(), name='stationdetail'),
    url(r'^concentrator/list/$', VConcentratorListAPIView.as_view(), name='concentratorlist'),
    url(r'^community/list/$', VCommunityListAPIView.as_view(), name='communitylist'),
    url(r'^pressure/list/$', VPressureListAPIView.as_view(), name='pressurelist'),
    url(r'^pressure/list/(?P<pk>\d+)/$', VPressureDetailAPIView.as_view(), name='pressuredetail'),
    url(r'^secondwater/list/$', VSecondwaterListAPIView.as_view(), name='secondwaterlist'),
    url(r'^watermeter/list/$', VWatermeterListAPIView.as_view(), name='watermeterlist'),
    url(r'^watermeter/list/(?P<pk>\d+)/$', VWatermeterDetailAPIView.as_view(), name='watermeterdetail'),
    url(r'^waterusertype/list/$', WaterUserTypeListAPIView.as_view(), name='waterusertypelist'),

    url(r'^metercomm/list/$', MetercommListAPIView.as_view(), name='metercommlist'),
    url(r'^meterparameter/list/$', MeterParameterListAPIView.as_view(), name='meterparameterlist'),
    url(r'^meterprotocol/list/$', MeterprotocolListAPIView.as_view(), name='meterprotocollist'),
]

dmam/api/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import url
from django.contrib import admin

from .views import (
    StationListAPIView,
    CommunityListAPIView,
    SecondWaterListAPIView,
    DMAListAPIView,
    dmabaseinfo,
    getDmaSelect,
)

app_name='devm-api'
urlpatterns = [
    # url(r'^user/oranizationtree/$', OrganizationListAPIView.as_view(), name='organlist'),
    # url(r'^create/$', PostCreateAPIView.as_view(), name='create'),
    # url(r'^(?P<slug>[\w-]+)/$', PostDetailAPIView.as_view(), name='detail'),
    # url(r'^(?P<slug>[\w-]+)/edit/$', PostUpdateAPIView.as_view(), name='update'),
    # url(r'^(?P<slug>[\w-]+)/delete/$', PostDeleteAPIView.as_view(), name='delete'),
    url(r'^stations/list/$', StationListAPIView.as_view(), name='stationlist'),

    url(r'^dma/getDmaSelect/$', getDmaSelect, name='dmaselect'),
    url(r'^dma/list/$', DMAListAPIView.as_view(), name='dmalist'),
    url(r'^district/dmabaseinfo/$', dmabaseinfo, name='dmabaseinfo'),

    url(r'^community/list/$', CommunityListAPIView.as_view(), name='communitylist'),

    url(r'^secondwater/list/$', SecondWaterListAPIView.as_view(), name='secondwaterlist'),

]

dmam/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views
from django.views.generic import TemplateView

from . import views

app_name = 'dmam'
urlpatterns = [
    
    #使用hplus页面布局时的首页
    # url(r'^$', TemplateView.as_view(template_name='hplus.html'),name='virvo_home'),
    url(r'^$', TemplateView.as_view(template_name='_vbase.html'),name='dma_home'),


    # tree list etc
    
    url(r'^district/dmatree/',views.dmatree,name='dmatree'),

    # dma管理 --dma分区管理
    url(r'^districtmanager/?$', views.DistrictMangerView.as_view(), name='districtmanager'),#组织和用户管理
    url(r'^district/add/?$',views.DistrictAddView.as_view(),name='districtadd'),
    url(r'^district/edit/(?P<pId>\w+)/?$',views.DistrictEditView.as_view(),name='districtedit'),
    url(r'^district/detail/(?P<pId>\w+)/?$',views.DistrictDetailView.as_view(),name='districtdetail'),
    url(r'^district/delete/?$',views.DistrictDeleteView.as_view(),name='districtdelete'),
    url(r'^district/dmabaseinfo/?$',views.dmabaseinfo,name='dmabaseinfo'),
    url(r'^district/dmabaseinfo/edit/(?P<pk>\w+)/?$',views.DMABaseinfoEditView.as_view(),name='dmabaseinfoedit'),
    url(r'^getdmamapusedata/?$',views.getdmamapusedata,name='getdmamapusedata'),
    url(r'^verifydmano/?$',views.verifydmano,name='verifydmano'),
    url(r'^verifydmaname/?$',views.verifydmaname,name='verifydmaname'),

    # dma 列表选择关联
    url(r'^getDmaSelect/?$',views.getDmaSelect,name='getDmaSelect'),

    #dma分区站点配置
    url(r'^district/assignstation/(?P<pk>\w+)/?$',views.DistrictAssignStationView.as_view(),name='districtassignstation'),
    url(r'^dmaStation/getdmastationsbyId/?$',views.getdmastationsbyId,name='getdmastationsbyId'),
    url(r'^dmaStation/saveDmaStation/?$',views.saveDmaStation,name='saveDmaStation'),

# dma 分区地图信息处理
    url(r'^district/saveDmaGisinfo/?$',views.saveDmaGisinfo,name='saveDmaGisinfo'),
    url(r'^district/getDmaGisinfo/?$',views.getDmaGisinfo,name='getDmaGisinfo'),
    

    #stations  
    url(r'^station/findUsertypes/?$',views.findUsertypes,name='findUsertypes'),
    url(r'^station/findUsertypeById/?$',views.findUsertypeById,name='findUsertypeById'),
    url(r'^station/updateOperation/?$',views.updateOperation,name='updateOperation'),
    url(r'^station/deleteOperation/?$',views.deleteOperation,name='deleteOperation'),
    url(r'^station/deleteOperationMore/?$',views.deleteOperationMore,name='deleteOperationMore'),
    
    url(r'^station/findusertypeByusertype/?$',views.findusertypeByusertype,name='findusertypeByusertype'),
    url(r'^station/findUsertypeCompare/?$',views.findUsertypeCompare,name='findUsertypeCompare'),
    
    url(r'^station/usertype/add/?$',views.usertypeadd,name='usertypeadd'),
    url(r'^station/usertype/edit/(?P<pk>[0-9]+)/?$',views.usertypeedit,name='usertypeedit'),

    url(r'^station/verifyusername/$',views.verifyusername,name='verifyusername'),
    
    url(r'^stationsmanager/?$', views.StationMangerView.as_view(), name='stationsmanager'),#组织和用户管理
    url(r'^stations/list/$',views.stationlist,name='stationlist'),
    url(r'^stations/add',views.StationAddView.as_view(),name='stationadd'),
    url(r'^stations/edit/(?P<pk>\w+)/?$',views.StationEditView.as_view(),name='stationedit'),
    url(r'^stations/delete/(?P<pk>[0-9]+)/?$',views.StationDeleteView.as_view(),name='stationdelete'),
    url(r'^stations/deletemore',views.stationdeletemore,name='stationdeletemore'),
    url(r'^dmastations/list/(?P<pk>\w+)/$',views.dmastationlist,name='dmastationlist'),
    url(r'^stations/import',views.StationImportView.as_view(),name='stationimport'),
    url(r'^stations/basetemp/download',views.stationtemplaatedownload,name='stationtemplaatedownload'),
    
    url(r'^station/getmeterlist/$',views.getmeterlist,name='getmeterlist'),
    url(r'^station/getmeterParam/$',views.getmeterParam,name='getmeterParam'),

    # url(r'^stations/export',views.stationexport,name='stationexport'),
    # url(r'^stations/import',views.StationImportView.as_view(),name='stationimport'),
    # url(r'^stations/download',views.download,name='download'),

    # url(r'^infoconfig/infoinput/importProgress',views.importProgress,name='importProgress'),

    # 二供管理
    url(r'^secondmanager/?$', views.SecondMangerView.as_view(), name='secondmanager'),
    url(r'^secondwater/list/$',views.secondwaterlist,name='secondwaterlist'),
    url(r'^secondwater/add',views.SecondWaterAddView.as_view(),name='secondwateradd'),
    url(r'^secondwater/edit/(?P<pk>\w+)/?$',views.SecondWaterEditView.as_view(),name='secondwateredit'),
    url(r'^secondwater/delete/(?P<pk>[0-9]+)/?$',views.SecondWaterDeleteView.as_view(),name='secondwaterdelete'),
    url(r'^secondwater/deletemore',views.secondwaterdeletemore,name='secondwaterdeletemore'),
    url(r'^secondwater/repetition/$',views.secondwater_repetition,name='secondwater_repetition'),
    
    # 视频管理
    url(r'^vediomanager/?$', views.VedioMangerView.as_view(), name='vediomanager'),
    # 车辆管理
    url(r'^vehiclemanager/?$', views.VehicleMangerView.as_view(), name='vehiclemanager'),

    # 小区管理
    url(r'^neighborhoodmanager/?$', views.NeighborhoodMangerView.as_view(), name='neighborhoodmanager'),
    url(r'^community/list/$',views.communitylist,name='communitylist'),
    url(r'^community/add',views.CommunityAddView.as_view(),name='communityadd'),
    url(r'^community/edit/(?P<pk>\w+)/?$',views.CommunityEditView.as_view(),name='communityedit'),
    url(r'^community/delete/(?P<pk>[0-9]+)/?$',views.CommunityDeleteView.as_view(),name='communitydelete'),
    url(r'^community/deletemore',views.communitydeletemore,name='communitydeletemore'),
    url(r'^community/repetition/$',views.community_repetition,name='community_repetition'),
    url(r'^community/getCommunitySelect/$',views.getCommunitySelect,name='getCommunitySelect'),



]

dmam/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

templates/dmam/communityadd.html
{% load staticfiles %}
<form id="addForm" role="form" action="{% url 'dmam:communityadd' %}" method="post" class="form-horizontal">{% csrf_token %}
    <div class="modal-header">
        <button type="button" id="doXAdd" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">新建小区</h4>
    </div>
    <div class="modal-body">
        <input  type="text" class="hidden" id="cid" name="cid" value="{{ cid }}" />
        <input  type="text" class="hidden" id="pid" name="pId" value="{{ pId }}"/>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label class="col-md-2 control-label" style="padding-right: 0px;"><label class="text-danger">*</label> 小区名称：</label>
                    <div class="col-md-4">
                        <input name="name" placeholder="请输入小区名称" type="text" maxlength="50" class="form-control" id="name"/>
                        <label id="name-error" style="display: none" class="error" for="name">请输小区名称</label>
                    </div>
                    <label class="col-md-2 control-label"><label class="text-danger">*</label> 所属组织：</label>
                    <div class="has-feedback col-md-4">
                        <input name="belongto" class="form-control" id="zTreeOrganSel"
                            placeholder="请选择所属企业" readonly="readonly" style="background-color: #fafafa; cursor: pointer;"  type="text"/>
                        <span class="fa fa-chevron-down form-control-feedback" aria-hidden="true" id="zTreeCitySelSpan"></span>
                        <div class="ztreeModelBox" id="zTreeContent">
                            <ul id="ztreeDemo" class="ztree"></ul>
                        </div>
                        <input id = "groupId" name = "groupId" type="text" hidden="true" />
                        <label id="error_label_add" class="error" style="display: none;"></label>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-2 control-label"><label class="text-danger">*</label> 集中器1：</label>
                    <div class="col-md-4">
                        <div class="input-group">
                            <input name="vconcentrator1" type="text" class="form-control" id="concentrator1">
                            <div class="input-group-btn">
                                <button type="button" class="btn btn-white dropdown-toggle"
                                    data-toggle="dropdown">
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu dropdown-menu-right" role="menu">
                                </ul>
                            </div>
                        </div>
                    </div>
                    <label class="col-md-2 control-label">集中器2：</label>
                    <div class="col-md-4">
                        <div class="input-group">
                            <input name="vconcentrator2" type="text" class="form-control" id="concentrator2">
                            <div class="input-group-btn">
                                <button type="button" class="btn btn-white dropdown-toggle"
                                    data-toggle="dropdown">
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu dropdown-menu-right" role="menu">
                                </ul>
                            </div>
                        </div>
                    </div>


                </div>

                <div class="form-group">
                    <label class="col-md-2 control-label"> 集中器3：</label>
                    <div class="col-md-4">
                        <div class="input-group">
                            <input name="vconcentrator3" type="text" class="form-control" id="concentrator3">
                            <div class="input-group-btn">
                                <button type="button" class="btn btn-white dropdown-toggle"
                                    data-toggle="dropdown">
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu dropdown-menu-right" role="menu">
                                </ul>
                            </div>
                        </div>
                    </div>
                    <label class="col-md-2 control-label">集中器4：</label>
                    <div class="col-md-4">
                        <div class="input-group">
                            <input name="vconcentrator4" type="text" class="form-control" id="concentrator4">
                            <div class="input-group-btn">
                                <button type="button" class="btn btn-white dropdown-toggle"
                                    data-toggle="dropdown">
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu dropdown-menu-right" role="menu">
                                </ul>
                            </div>
                        </div>
                    </div>


                </div>
                <div class="form-group">
                    <label class="col-md-2 control-label">位置描述：</label>
                    <div class="col-md-10">
                        <input name="address" id="address" placeholder="请输入安装位置描述" type="text" class="form-control" />
                    </div>
                    
                </div>
                
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button id="doSubmit"  class="btn btn-primary" type="button">
            <strong>提 交</strong>
        </button>
        <button id="doCloseAdd" type="button" class="btn btn-default" data-dismiss="modal">
            <strong>关 闭</strong>
        </button>
    </div>
    <input  type="hidden" value="ef6c759b-ef14-46f7-bec1-5819d0c322fa" name="avoidRepeatSubmitToken" id="avoidRepeatSubmitToken">
</form>
<!-- <script type="text/javascript" src="/clbs/resources/js/sendAjax.js"></script> -->
<script src="{% static 'virvo/resources/js/sendAjax.js' %}"></script>

<script>
var deviceNumberNull = "\u7EC8\u7AEF\u53F7\u4E0D\u80FD\u4E3A\u7A7A";
    var deviceNumberError = "\u8BF7\u8F93\u5165\u5B57\u6BCD/\u6570\u5B57/\u4E0B\u5212\u7EBF/\u77ED\u6760\uFF0C\u8303\u56F4\uFF08\u8F66\uFF097~15\uFF08\u4EBA\uFF091~20";
    var deviceNumberExists = "\u7EC8\u7AEF\u53F7\u5DF2\u5B58\u5728";
    var deviceTypeNull="\u901A\u8BAF\u7C7B\u578B\u4E0D\u80FD\u4E3A\u7A7A";

    var publicSize6="\u957F\u5EA6\u4E0D\u8D85\u8FC76\u4F4D";
    var publicSize10="\u957F\u5EA6\u4E0D\u8D85\u8FC710\u4F4D";
    var publicSize20="\u957F\u5EA6\u4E0D\u8D85\u8FC720\u4F4D";
    var publicSize50="\u957F\u5EA6\u4E0D\u8D85\u8FC750\u4F4D";
    var publicSize64="\u957F\u5EA6\u4E0D\u8D85\u8FC764\u4F4D";
    var publicSize100="\u957F\u5EA6\u4E0D\u8D85\u8FC7100\u4F4D";
    var phoneError = "\u770B\u8D77\u6765\u4E0D\u50CF\u624B\u673A\u53F7\u5462";
    var publicNull = "\u4E0D\u80FD\u4E3A\u7A7A";
</script>

<script src="{% static 'virvo/wro/comunityAdd.js' %}"></script>

templates/dmam/communityedit.html
{% load staticfiles %}
<form id="editForm" role="form" action="{% url 'dmam:communityedit' object.pk %}" method="post" class="form-horizontal">{% csrf_token %}
    <div class="modal-header">
        <button type="button" id="doXEdit" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">编辑小区</h4>
    </div>
    <div class="modal-body">
        <input  type="text" class="hidden" id="cid" name="cid" value="{{ cid }}" />
        <input  type="text" class="hidden" id="pid" name="pId" value="{{ pId }}"/>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label class="col-md-2 control-label" style="padding-right: 0px;"><label class="text-danger">*</label> 小区名称：</label>
                    <div class="col-md-4">
                        <input name="name" value="{{ form.name.value|default:'' }}" type="text" maxlength="50" class="form-control" id="name"/>
                        <label id="name-error" style="display: none" class="error" for="name">请输小区名称</label>
                    </div>
                    <label class="col-md-2 control-label"><label class="text-danger">*</label> 所属组织：</label>
                    <div class="has-feedback col-md-4">
                        <input name="belongto" class="form-control" id="zTreeOrganSel" value="{{ form.belongto.value|default:'' }}"
                             readonly="readonly" style="background-color: #fafafa; cursor: pointer;"  type="text"/>
                        <span class="fa fa-chevron-down form-control-feedback" aria-hidden="true" id="zTreeCitySelSpan"></span>
                        <div class="ztreeModelBox" id="zTreeContent">
                            <ul id="ztreeDemo" class="ztree"></ul>
                        </div>
                        <input id = "groupId" name = "groupId" type="text" hidden="true" />
                        <label id="error_label_add" class="error" style="display: none;"></label>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-2 control-label"><label class="text-danger">*</label> 集中器1：</label>
                    <div class="col-md-4">
                        <div class="input-group">
                            <input name="vconcentrator1" value="{{ form.vconcentrator1.value|default:'' }}" type="text" class="form-control" id="concentrator1">
                            <div class="input-group-btn">
                                <button type="button" class="btn btn-white dropdown-toggle"
                                    data-toggle="dropdown">
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu dropdown-menu-right" role="menu">
                                </ul>
                            </div>
                        </div>
                    </div>
                    <label class="col-md-2 control-label">集中器2：</label>
                    <div class="col-md-4">
                        <div class="input-group">
                            <input name="vconcentrator2" value="{{ form.vconcentrator2.value|default:'' }}" type="text" class="form-control" id="concentrator2">
                            <div class="input-group-btn">
                                <button type="button" class="btn btn-white dropdown-toggle"
                                    data-toggle="dropdown">
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu dropdown-menu-right" role="menu">
                                </ul>
                            </div>
                        </div>
                    </div>


                </div>

                <div class="form-group">
                    <label class="col-md-2 control-label"> 集中器3：</label>
                    <div class="col-md-4">
                        <div class="input-group">
                            <input name="vconcentrator3" value="{{ form.vconcentrator3.value|default:'' }}" type="text" class="form-control" id="concentrator3">
                            <div class="input-group-btn">
                                <button type="button" class="btn btn-white dropdown-toggle"
                                    data-toggle="dropdown">
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu dropdown-menu-right" role="menu">
                                </ul>
                            </div>
                        </div>
                    </div>
                    <label class="col-md-2 control-label">集中器4：</label>
                    <div class="col-md-4">
                        <div class="input-group">
                            <input name="vconcentrator4" value="{{ form.vconcentrator4.value|default:'' }}" type="text" class="form-control" id="concentrator4">
                            <div class="input-group-btn">
                                <button type="button" class="btn btn-white dropdown-toggle"
                                    data-toggle="dropdown">
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu dropdown-menu-right" role="menu">
                                </ul>
                            </div>
                        </div>
                    </div>


                </div>
                <div class="form-group">
                    <label class="col-md-2 control-label">位置描述：</label>
                    <div class="col-md-10">
                        <input name="address" id="address" value="{{ form.address.value|default:'' }}" type="text" class="form-control" />
                    </div>
                    
                </div>
                
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button id="doSubmit"  class="btn btn-primary" type="button">
            <strong>提 交</strong>
        </button>
        <button id="doCloseAdd" type="button" class="btn btn-default" data-dismiss="modal">
            <strong>关 闭</strong>
        </button>
    </div>
    <input  type="hidden" value="ef6c759b-ef14-46f7-bec1-5819d0c322fa" name="avoidRepeatSubmitToken" id="avoidRepeatSubmitToken">
</form>
<!-- <script type="text/javascript" src="/clbs/resources/js/sendAjax.js"></script> -->
<script src="{% static 'virvo/resources/js/sendAjax.js' %}"></script>

<script>
var deviceNumberNull = "\u7EC8\u7AEF\u53F7\u4E0D\u80FD\u4E3A\u7A7A";
    var deviceNumberError = "\u8BF7\u8F93\u5165\u5B57\u6BCD/\u6570\u5B57/\u4E0B\u5212\u7EBF/\u77ED\u6760\uFF0C\u8303\u56F4\uFF08\u8F66\uFF097~15\uFF08\u4EBA\uFF091~20";
    var deviceNumberExists = "\u7EC8\u7AEF\u53F7\u5DF2\u5B58\u5728";
    var deviceTypeNull="\u901A\u8BAF\u7C7B\u578B\u4E0D\u80FD\u4E3A\u7A7A";

    var publicSize6="\u957F\u5EA6\u4E0D\u8D85\u8FC76\u4F4D";
    var publicSize10="\u957F\u5EA6\u4E0D\u8D85\u8FC710\u4F4D";
    var publicSize20="\u957F\u5EA6\u4E0D\u8D85\u8FC720\u4F4D";
    var publicSize50="\u957F\u5EA6\u4E0D\u8D85\u8FC750\u4F4D";
    var publicSize64="\u957F\u5EA6\u4E0D\u8D85\u8FC764\u4F4D";
    var publicSize100="\u957F\u5EA6\u4E0D\u8D85\u8FC7100\u4F4D";
    var phoneError = "\u770B\u8D77\u6765\u4E0D\u50CF\u624B\u673A\u53F7\u5462";
    var publicNull = "\u4E0D\u80FD\u4E3A\u7A7A";

    var old_name = "{{ form.name.value|default:'' }}"
    var v1name = "{{ form.belongto.value|default:'' }}"
    console.log(v1name)
    
</script>

<script src="{% static 'virvo/wro/comunityEdit.js' %}"></script>

templates/dmam/importstation.html
{% load staticfiles %}
<form id="importForm" role="form" action="/dmam/stations/import" method="post"
    class="form-horizontal" enctype="multipart/form-data">{% csrf_token %}
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"
            aria-hidden="true">&times;</button>
        <h4 class="modal-title">导入站点</h4>
    </div>
    <div class="modal-body">
        <a class="btn btn-primary"  href="/dmam/stations/basetemp/download"><strong>下载模板</strong></a>
        <br/><br/>
        <div class="inpFilePhoto">
            <input type="file" id="excelPath" name="file" /><strong>导入文件</strong>
        </div>
        <div class="fileNameShow"></div>
        <div class="progress" style="display:none;">
          <div class="progress-bar progress-bar-progress" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
            0%
          </div>
        </div>
    </div>
    <!-- <input type="hidden" id="X-Progress-ID" name="X-Progress-ID" value=""/>

    <input type="hidden" id="id" name="id" value=""/> -->

    <div class="modal-footer modal-footer-martop">
        <button class="btn btn-primary" type="button" id="doSubmits">
            <strong>提 交</strong>
        </button>
        <button type="button" class="btn btn-default" id="close" data-dismiss="modal" >
            <strong>关 闭</strong>
        </button>
    </div>
</form>

{% block javascript %}
<script src="{% static 'virvo/resources/js/importFileV.js' %}"></script>
<script type="text/javascript">
$(function(){
    $("#close").click(function(){
        $("#importForm").hide();
    })
})
</script>
{% endblock %}

templates/dmam/vehiclemanager.html
 
{% extends '_vbase.html' %}


{% load staticfiles %}

{% block main_content %}


<div class="row">
    <div class="col-md-12">
        <p style="margin-top: 100px;margin-left: 400px;font-weight: 600;font-size: 36px;">数据维护中......</p>
    </div>
</div>



{% endblock %}




{% block javascript %}

{% endblock %}