api/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from api.entm.users.views import UserViewSet

from django.conf.urls import url
from django.contrib import admin

from .views import (
    OrganizationListAPIView,
    OrganizationDetailAPIView,
    MyRoleListAPIView,
    UserListAPIView,
    SimCardListAPIView,
    MeterListAPIView,
    StationListAPIView,
    StationDetailAPIView,
    VConcentratorListAPIView,
    VCommunityListAPIView,
    VPressureListAPIView,
    VPressureDetailAPIView,
    VSecondwaterListAPIView,
    VWatermeterListAPIView,
    VWatermeterDetailAPIView,
    WaterUserTypeListAPIView,
    MetercommListAPIView,
    MeterParameterListAPIView,
    MeterprotocolListAPIView,
    PersonalizedListAPIView,
)



router = routers.DefaultRouter()
router.register(r'users', UserViewSet)

app_name='api'
urlpatterns = [
    url(r'^', include(router.urls)),
    # url(r'^auth/', include('rest_auth.urls')),

    url(r'^personlized/list/$', PersonalizedListAPIView.as_view(), name='personlized'),
    url(r'^organizations/list/$', OrganizationListAPIView.as_view(), name='organlist'),
    url(r'^organizations/list/(?P<pk>\d+)/$', OrganizationDetailAPIView.as_view(), name='detail'),
    url(r'^role/list/$', MyRoleListAPIView.as_view(), name='myrolelist'),
    url(r'^user/list/$', UserListAPIView.as_view(), name='userlist'),
    url(r'^simcard/list/$', SimCardListAPIView.as_view(), name='simcardlist'),
    url(r'^meter/list/$', MeterListAPIView.as_view(), name='meterlist'),
    url(r'^station/list/$', StationListAPIView.as_view(), name='stationlist'),
    url(r'^station/list/(?P<pk>\d+)/$', StationDetailAPIView.as_view(), name='stationdetail'),
    url(r'^concentrator/list/$', VConcentratorListAPIView.as_view(), name='concentratorlist'),
    url(r'^community/list/$', VCommunityListAPIView.as_view(), name='communitylist'),
    url(r'^pressure/list/$', VPressureListAPIView.as_view(), name='pressurelist'),
    url(r'^pressure/list/(?P<pk>\d+)/$', VPressureDetailAPIView.as_view(), name='pressuredetail'),
    url(r'^secondwater/list/$', VSecondwaterListAPIView.as_view(), name='secondwaterlist'),
    url(r'^watermeter/list/$', VWatermeterListAPIView.as_view(), name='watermeterlist'),
    url(r'^watermeter/list/(?P<pk>\d+)/$', VWatermeterDetailAPIView.as_view(), name='watermeterdetail'),
    url(r'^waterusertype/list/$', WaterUserTypeListAPIView.as_view(), name='waterusertypelist'),

    url(r'^metercomm/list/$', MetercommListAPIView.as_view(), name='metercommlist'),
    url(r'^meterparameter/list/$', MeterParameterListAPIView.as_view(), name='meterparameterlist'),
    url(r'^meterprotocol/list/$', MeterprotocolListAPIView.as_view(), name='meterprotocollist'),
]

devm/api/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import url
from django.contrib import admin

from .views import (
    SimCardListAPIView,
    MeterListAPIView,
    VConcentratorListAPIView,
    VPressureListAPIView,
    getConcentratorSelect,
    getCommunitySelect,
    getSimcardSelect,
    getIMEISelect,
    MeterParameterListAPIView,
    getCommandParam,
    getpressureSelect,
    getMeterSelect,
)

app_name='devm-api'
urlpatterns = [
    # url(r'^user/oranizationtree/$', OrganizationListAPIView.as_view(), name='organlist'),
    # url(r'^create/$', PostCreateAPIView.as_view(), name='create'),
    # url(r'^(?P<slug>[\w-]+)/$', PostDetailAPIView.as_view(), name='detail'),
    # url(r'^(?P<slug>[\w-]+)/edit/$', PostUpdateAPIView.as_view(), name='update'),
    # url(r'^(?P<slug>[\w-]+)/delete/$', PostDeleteAPIView.as_view(), name='delete'),

    url(r'^simcard/list/$', SimCardListAPIView.as_view(), name='simcardlist'),

    url(r'^meter/list/$', MeterListAPIView.as_view(), name='meterlist'),

    url(r'^concentrator/list/$', VConcentratorListAPIView.as_view(), name='concentratorlist'),


    url(r'^pressure/list/$', VPressureListAPIView.as_view(), name='pressurelist'),
    url(r'^pressure/getpressureSelect',getpressureSelect,name='getpressureSelect'),

    url(r'^concentrator/getConcentratorSelect',getConcentratorSelect,name='getConcentratorSelect'),
    url(r'^community/getCommunitySelect',getCommunitySelect,name='getConcentratorSelect'),
    url(r'^simcard/getSimcardSelect',getSimcardSelect,name='getSimcardSelect'),
    url(r'^simcard/getIMEISelect',getIMEISelect,name='getConcentratorSelect'),
    url(r'^meter/getMeterSelect',getMeterSelect,name='getMeterSelect'),

    # 参数指令
    # url(r'^paramsmanager/?$', views.ParamsMangerView.as_view(), name='paramsmanager'),
    url(r'^paramsmanager/command/list/?$', MeterParameterListAPIView.as_view(), name='commandlist'),
    # url(r'^paramsmanager/command/saveCommand/?$', views.saveCommand, name='saveCommand'),
    # url(r'^paramsmanager/command/getCommandTypes/?$', views.getCommandTypes, name='getCommandTypes'),
    url(r'^paramsmanager/command/getCommandParam/?$', getCommandParam, name='getCommandParam'),
    # url(r'^paramsmanager/command/getReferCommand/?$', views.getReferCommand, name='getReferCommand'),

]

devm/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views
from django.views.generic import TemplateView

from . import views

app_name = 'devm'
urlpatterns = [
    
    #使用hplus页面布局时的首页
    # url(r'^$', TemplateView.as_view(template_name='hplus.html'),name='virvo_home'),
    url(r'^$', TemplateView.as_view(template_name='_vbase.html'),name='dma_home'),




    #meters   表具管理
    url(r'^meter/repetition/$',views.repetition,name='repetition'),

    url(r'^metermanager/?$', views.MeterMangerView.as_view(), name='metermanager'),#组织和用户管理
    url(r'^meter/list/$',views.meterlist,name='meterlist'),
    url(r'^meter/add',views.MeterAddView.as_view(),name='meteradd'),
    url(r'^meter/edit/(?P<pk>\w+)/?$',views.MeterEditView.as_view(),name='meteredit'),
    url(r'^meter/delete/(?P<pk>[0-9]+)/?$',views.MeterDeleteView.as_view(),name='meterdelete'),
    url(r'^meter/deletemore',views.meterdeletemore,name='meterdeletemore'),
    url(r'^meter/getMeterSelect/$',views.getMeterSelect,name='getMeterSelect'),
    
    #simcards   
    url(r'^simcard/repetition/$',views.simcard_repetition,name='simcard_repetition'),
    url(r'^simcard/getSimcardSelect/$',views.getSimcardSelect,name='getSimcardSelect'),
    url(r'^simcard/getIMEISelect/$',views.getIMEISelect,name='getIMEISelect'),
    url(r'^simcard/getSimRelated/$',views.getSimRelated,name='getSimRelated'),
    url(r'^simcard/releaseRelate/$',views.releaseRelate,name='releaseRelate'),

    url(r'^simcardmanager/?$', views.SimCardMangerView.as_view(), name='simcardmanager'),#组织和用户管理
    url(r'^simcard/list/$',views.simcardlist,name='simcardlist'),
    url(r'^simcard/add',views.SimCardAddView.as_view(),name='simcardadd'),
    url(r'^simcard/edit/(?P<pk>\w+)/?$',views.SimCardEditView.as_view(),name='simcardedit'),
    url(r'^simcard/delete/(?P<pk>[0-9]+)/?$',views.SimCardDeleteView.as_view(),name='simcarddelete'),

    url(r'^simcard/export',views.simcardexport,name='simcardexport'),
    url(r'^simcard/import',views.SimcardImportView.as_view(),name='simcardimport'),
    url(r'^simcard/basetemp/download',views.simcarddownload,name='simcarddownload'),


    # 压力管理
    url(r'^pressuremanager/?$', views.PressureMangerView.as_view(), name='pressuremanager'),
    url(r'^pressure/list/$',views.pressurelist,name='pressurelist'),
    url(r'^pressure/add',views.VPressureAddView.as_view(),name='pressureadd'),
    url(r'^pressure/edit/(?P<pk>\w+)/?$',views.VPressureEditView.as_view(),name='pressureedit'),
    url(r'^pressure/delete/(?P<pk>[0-9]+)/?$',views.VPressureDeleteView.as_view(),name='pressuredelete'),
    url(r'^pressure/deletemore',views.pressuredeletemore,name='pressuredeletemore'),
    url(r'^pressure/pressure_repetition/$',views.pressure_repetition,name='pressure_repetition'),

    # 消防栓管理
    url(r'^fireboltmanager/?$', views.FireboltMangerView.as_view(), name='fireboltmanager'),

    # 集中器管理
    url(r'^concentratormanager/?$', views.ConcentratorMangerView.as_view(), name='concentratormanager'),
    url(r'^concentrator/list/$',views.concentratorlist,name='concentratorlist'),
    url(r'^concentrator/add',views.ConcentratorAddView.as_view(),name='concentratoradd'),
    url(r'^concentrator/edit/(?P<pk>\w+)/?$',views.ConcentratorEditView.as_view(),name='concentratoredit'),
    url(r'^concentrator/config/(?P<pk>\w+)/?$',views.ConcentratorConfigView.as_view(),name='concentratorconfig'),
    url(r'^concentrator/config/(?P<pk>\w+)/nb/?$',views.ConcentratorConfigNBView.as_view(),name='concentratorconfig-nb'),
    url(r'^concentrator/delete/(?P<pk>[0-9]+)/?$',views.ConcentratorDeleteView.as_view(),name='concentratordelete'),
    url(r'^concentrator/deletemore',views.concentratordeletemore,name='concentratordeletemore'),
    url(r'^concentrator/repetition/$',views.concentrator_repetition,name='concentrator_repetition'),
    url(r'^concentrator/repetition_commaddr/$',views.repetition_commaddr,name='repetition_commaddr'),
    url(r'^concentrator/getConcentratorSelect/$',views.getConcentratorSelect,name='getConcentratorSelect'),
    url(r'^concentrator/getConcentratorByComunityId/$',views.getConcentratorByComunityId,name='getConcentratorByComunityId'),
    url(r'^concentrator/getwatermeterlistbyconId/$',views.getwatermeterlistbyconId,name='getConcentragetwatermeterlistbyconIdtorByComunityId'),
    url(r'^concentrator/getConcentratorReplyStatus/$',views.getConcentratorReplyStatus,name='getConcentratorReplyStatus'),
    url(r'^concentrator/deletemeter_bystatus/$',views.deletemeter_bystatus,name='deletemeter_bystatus'),
    url(r'^concentrator/clearmeter_bystatus/$',views.clearmeter_bystatus,name='clearmeter_bystatus'),
    # url(r'^concentrator/add',views.ConcentratorAddView.as_view(),name='concentratoradd'),
    # url(r'^concentrator/edit/(?P<pk>\w+)/?$',views.ConcentratorEditView.as_view(),name='concentratoredit'),
    # url(r'^concentrator/delete/(?P<pk>[0-9]+)/?$',views.ConcentratorDeleteView.as_view(),name='concentratordelete'),
    # url(r'^concentrator/deletemore',views.concentratordeletemore,name='concentratordeletemore'),

    # 参数指令
    url(r'^paramsmanager/?$', views.ParamsMangerView.as_view(), name='paramsmanager'),
    url(r'^paramsmanager/command/list/?$', views.commandlist, name='commandlist'),
    url(r'^paramsmanager/command/saveCommand/?$', views.saveCommand, name='saveCommand'),
    url(r'^paramsmanager/command/getCommandTypes/?$', views.getCommandTypes, name='getCommandTypes'),
    url(r'^paramsmanager/command/getCommandParam/?$', views.getCommandParam, name='getCommandParam'),
    url(r'^paramsmanager/command/getReferCommand/?$', views.getReferCommand, name='getReferCommand'),

    
]

devm/models.py
# -*- coding:utf-8 -*-

from django.db import models

# Create your models here.

templates/devm/concentrator_nbconfig.html
{% load staticfiles %}
<style type="text/css">
    /*div.dataTables_wrapper{overflow:hidden;user-select:text!important;-ms-user-select:text!important;-moz-user-select:text!important;-webkit-user-select:text!important}*/
    .hidevalue {
      display: none;
    }

    .modal-body {
        position: relative;
        padding: 20px;
        height: 200px;
        overflow-y: scroll;
    }
  </style>
  
    <div class="modal-header">
        <button id="doXEdit" type="button" class="close" data-dismiss="modal"
            aria-hidden="true">&times;</button>
            <input type="hidden" id="concentrator_id" value="{{ object.commaddr}}">
            <input type="hidden" id="concentrator_commaddr" value="{{ object.commaddr }}">
        <h4 class="modal-title">配置集中器-NB<span>:{{ object.name }}</span></h4>
    </div>
    <div class="modal-body">
        <div class="row">
            <div class="col-md-6" style="border:1px solid olive;">
                <div>
                    <input  class="groupchecks" type="checkbox" value="group1" id="group1"  onclick="configCentrator.checkGroup(this.value)" checked>
                </div>
                <div class="form-group">
                    <div class="col-md-5">
                        <label for="discrete_start">离散上报起始时间:</label>

                    </div>
                    <div class="col-md-7">
                        <input type="text" id="discrete_start" name="discrete_start" value="0"><span>点</span>
                        <label id="discrete_start-error" style="display: none" class="error" for="name">请输入0-23</label>
                    </div>
                    
                </div>
                <div class="form-group">
                    <div class="col-md-5">
                        <label for="discrete_time">离散上报时长:</label>

                    </div>
                    <div class="col-md-7">
                        <input type="text" id="discrete_time" name="discrete_time" value="0"><span>分</span>
                        <label id="discrete_time-error" style="display: none" class="error" for="name">请输入0-255</label>
                    </div>
                    
                </div>
                <div class="form-group">
                    <div class="col-md-5">

                        <label for="report_period">上报间隔:</label>
                    </div>
                    <div class="col-md-7">
                        <input type="text" id="report_period" name="report_period" value="1"><span>时</span>
                        <label id="report_period-error" style="display: none" class="error" for="name">请输入1-25</label>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-5">
                        <label for="sample_period">采样间隔:</label>
                    </div>
                    <div class="col-md-7">
                        <input type="text" id="sample_period" name="sample_period" value="0"><span>分</span>
                        <label id="sample_period-error" style="display: none" class="error" for="sample_period">请输入0-255</label>
                    </div>
                </div>
                
                
                
            </div>
            
            <div class="col-md-6">
                <div style="border:1px solid olive;">
                    <div>
                        <input type="checkbox" class="groupchecks" value="group2" id="group2"   onclick="configCentrator.checkGroup(this.value)" />
                    </div>
                    
                    <div >
                        <label  for="valve-wash" > 洗阀：</label>
                        <!-- <div class="col-md-9"> -->
                            <!-- <input name="model" id="model" type="text" class="form-control" /> -->
                            <select name="valve-wash" id="valve-wash" autocomplete="off"   >
                                <!-- <option  value="">- 请选择类型 -</option> -->
                                <option value="0">允许</option>
                                <option value="1">禁止</option>
                                
                            </select>
                        <!-- </div> -->
                    </div>
                    
                    <div >
                        <label  > 控阀：</label>
                        <!-- <div class="col-md-9"> -->
                            <!-- <input name="model" id="model" type="text" class="form-control" /> -->
                            <select name="valve-control" id="valve-control" autocomplete="off"  >
                                <!-- <option  value="">- 请选择类型 -</option> -->
                                <option value="0">开阀</option>
                                <option value="1">关阀</option>
                                
                            </select>
                        <!-- </div> -->
                    </div>
                
    
                </div>

                <!-- group3 -->
                <div style="border:1px solid olive;">
                    <div>
                        <input class="groupchecks" type="checkbox"  value="group3" id="group3"   onclick="configCentrator.checkGroup(this.value)">
                    </div>
                    <div class="form-group" >
                        
                        <label class="control-label"> 校准水量：</label>
                        <input type="text" id="calibration" name="calibration"><span>m³</span>
                    </div>
    
                    
                </div>

                <!-- send btn -->
                <div style="margin-top: 20px;">
            
                    <button class="btn btn-default " style="margin-left: 10px;"  id="sendBtn">发送</button>
        
                </div>

                
            </div>

            
            
        </div>    
        <!-- end row --> 
        
        
        

        <div style="overflow: auto;width: 100%;">
            
            <table id="concentrator_watermeter"
                class="table table-striped table-bordered table-hover checkTable"
                cellspacing="0" >
                <thead>
                    <tr>
                        <th>序号</th>
                        <!-- <th><input name="select_all" value="1" type="checkbox"></th> -->
                        <th><input type="checkbox" id="checkAll"  onclick="configCentrator.checkAll(this)"></th>
                        <th>操作</th>
                        <th>水表编号</th>
                        <th>状态</th>
                        <th style="display: none;">deviceid</th>
                        <th style="display: none;">运营商</th>
                        <th style="display: none;">wateraddr</th>
                        
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>
    <div class="modal-footer">
        
        <!-- <button class="btn btn-primary" type="button" id="doSubmit">
            <strong>提 交</strong>
        </button> -->
        <button id="doCloseAdd" type="button" class="btn btn-default" data-dismiss="modal">
            <strong>关 闭</strong>
        </button>
    </div>
    

<script src="{% static 'virvo/resources/js/sendAjax.js' %}"></script>

<script>
    

</script>

<script src="{% static 'virvo/resources/js/bootstrap/js/bootstrap-table.min.js' %}"></script>
<script src="{% static 'virvo/resources/js/layui/layer/layer.js' %}"></script>
<script src="{% static 'virvo/wro/concentratorConfig-nb.js' %}"></script>

templates/devm/pressureedit.html
{% load staticfiles %}
<form id="editForm" role="form" action="{% url 'devm:pressureedit' object.pk %}" method="post" class="form-horizontal">{% csrf_token %}
    <div class="modal-header">
        <button id="doXEdit" type="button" class="close" data-dismiss="modal"
            aria-hidden="true">&times;</button>
        <h4 class="modal-title">修改压力表信息</h4>
    </div>
    <div class="modal-body">
        <div class="row">
            <div class="col-md-12">
                <div id="deviceNumberGroup" class="form-group">
                    <label class="col-md-2 control-label"><label
                        class="text-danger">*</label> 表具编号：</label>
                    <div class="col-md-4">
                        <input name="serialnumber" value="{{ form.serialnumber.value|default:'' }}" type="text" id= "serialnumber"
                            class="form-control" />
                        <label id="serialnumber-error" style="display: none" class="error" for="serialnumber">请输入表具编号</label>
                    </div>
                    <label class="col-md-2 control-label"><label class="text-danger">*</label> SIM卡号：</label>
                    <div class="col-sm-4 col-md-4 form-group" style="padding-top:10px; margin:0px;">
                        <div style="position:relative;">
                            <span style="overflow:hidden;">
                                <input type="hidden" id="commaddr" name="commaddr" value="{{ form.commaddr.value|default:'' }}"/>
                                </span>
                                <div class="input-group">
                                    <input value="{{ form.simid.value|default:'' }}"  type="text" placeholder="" class="form-control" maxlength="20" id="sims" name="simid" readonly="true">
                                    
                                    <div class="input-group-btn">
                                        <!-- <input type="hidden" class="hidenSubmitControl"/> -->
                                      <button type="button" id="button" class="btn btn-white dropdown-toggle disabled loading-state-button" data-toggle="dropdown">
                                          <i class="fa fa-spinner loading-state"></i>
                                      </button>
                                      <ul class="dropdown-menu dropdown-menu-right" role="menu"  style="width:100%">
                                      </ul>
                                    </div>
                                </div>
                        </div>
                    </div>
                    
                </div>
                
                <div class="form-group">
                    <label class="col-md-2 control-label"> 型号：</label>
                    <div class="col-md-4">
                        <input name="version" value="{{ form.version.value|default:'' }}"  type="text" id= "version" class="form-control" />
                        <!-- <label id="deviceNumber-error" style="display: none" class="error" for="deviceNumber">请输入终端号，范围：7~15</label> -->
                    </div>
                    <label class="col-md-2 control-label"><label class="text-danger">*</label> 所属组织：</label>
                    <div class="has-feedback col-md-4">
                        <input name="belongto" class="form-control" id="zTreeOrganSel"
                            value="{{ form.belongto.value|default:'' }}" readonly="readonly" style="background-color: #fafafa; cursor: pointer;"  type="text"/>
                        <span class="fa fa-chevron-down form-control-feedback" aria-hidden="true" id="zTreeCitySelSpan"></span>
                        <div class="ztreeModelBox" id="zTreeContent">
                            <ul id="ztreeDemo" class="ztree"></ul>
                        </div>
                        <input id = "groupId" name = "groupId" type="text" hidden="true" />
                        <label id="error_label_add" class="error" style="display: none;"></label>
                    </div>
                </div>
                
                <div class="form-group">
                    <label class="col-md-2 control-label"><label class="text-danger">*</label> 类型：</label>
                    <div class="col-md-4">
                        <!-- <input id = "metertype" name = "metertype" type="text" hidden="true" /> -->
                        <select name="metertype" id="metertype" autocomplete="off" value="{{ form.metertype.value|default:'' }}"  class="form-control">
                            <option  value="0">电磁水表</option>
                            <option  value="1">超声水表</option>
                            <option  value="2">机械水表</option>
                            <option  value="3">插入电磁</option>
                            
                        </select>
                    </div>
                    <label class="col-md-2 control-label"><label class="text-danger">*</label> 通讯协议：</label>
                    <div class="col-md-4">
                        <select name="protocol" value="{{ form.protocol.value|default:'' }}" id="protocol" autocomplete="off"  class="form-control">
                            <option  value="0">平台协议</option>
                            <option  value="1">和达协议</option>
                            <option  value="2">安信协议</option>
                            <option  value="3">手抄协议01</option>
                            
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-2 control-label">制造厂商：</label>
                    <div class="col-md-4">
                        <input name="manufacturer" id="manufacturer" value="{{ form.manufacturer.value|default:'' }}" type="text" class="form-control" />
                    </div>
                    <label class="col-md-2 control-label"><label
                        class="text-danger">*</label> 检修周期：</label>
                    <div class="col-md-4">
                        <select name="check_cycle" id="check_cycle" value="{{ form.check_cycle.value|default:'' }}" autocomplete="off" class="form-control">
                            <option  value="1">1年</option>
                            <option  value="2">2年</option>
                            <option  value="3">3年</option>
                            <option  value="4">4年</option>
                            <option  value="5">5年</option>
                            
                        </select>
                    </div>
                </div>
                <br>
                
                <div class="form-group">
                    <label class="col-md-2 control-label"> 表名称：</label>
                    <div class="col-md-4">
                        <input name="username" id="username" value="{{ form.username.value|default:'' }}" type="text" class="form-control" />
                    </div>
                    <label class="col-md-2 control-label">坐标体系：</label>
                    <div class="col-md-4">
                        <!-- <input type="hidden" id="coorTypeVal" name="coortype" > -->
                        <select id="coorType" class="form-control" name="coortype"  value="{{ form.coortype.value|default:'' }}">
                            <option value="WGS84">地球坐标</option>
                            <option value="GCJ-02">火星坐标</option>
                            <option value="BD-09">百度坐标</option>
                            <option value="IAG75">西安坐标</option>
                            <option value="CGCS2000">大地坐标</option>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-2 control-label"> 经度：</label>
                    <div class="col-md-4">
                        <input name="lng" value="{{ form.lng.value|default:'' }}" type="text" maxlength="50" class="form-control" id="lng">
                    </div>
                    <label class="col-md-2 control-label">纬度：</label>
                    <div class="col-md-4">
                        <input name="lat" value="{{ form.lat.value|default:'' }}" type="text" maxlength="50" class="form-control" id="lat">
                    </div>
                </div>
                
                
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <!-- <div id = "bindMsg" hidden="true" style="text-align:left;color:red;">
            <p> 注 ： 该终端已和监控对象绑定，终端号和通讯类型不允许修改，如需修改请先解除绑定！</p>
        </div> -->
        <div class=" pull-left" style="margin-left: 100px;">

            <label class="radio-inline"> <input type="radio" name="state" id="isRadio" value="1" > 启用</label>
            <label class="radio-inline"> <input type="radio" name="state" id="noRadio" value="0"> 停用</label>
        </div>
        <button class="btn btn-primary" type="button" id="doSubmit">
            <strong>提 交</strong>
        </button>
        <button id="doCloseEdit" type="button" class="btn btn-default" data-dismiss="modal">
            <strong>关 闭</strong>
        </button>
    </div>
</form>
<script src="{% static 'virvo/resources/js/sendAjax.js' %}"></script>
<script>
    var deviceNumberNull = "\u7EC8\u7AEF\u53F7\u4E0D\u80FD\u4E3A\u7A7A";
    var deviceNumberError = "\u8BF7\u8F93\u5165\u5B57\u6BCD/\u6570\u5B57\uFF0C\u8303\u56F4\uFF08\u8F66\uFF097~15\uFF08\u4EBA\uFF091~20";
    var deviceNumberExists = "\u7EC8\u7AEF\u53F7\u5DF2\u5B58\u5728";
    var deviceTypeNull="\u901A\u8BAF\u7C7B\u578B\u4E0D\u80FD\u4E3A\u7A7A";

    var publicSize6="\u957F\u5EA6\u4E0D\u8D85\u8FC76\u4F4D";
    var publicSize10="\u957F\u5EA6\u4E0D\u8D85\u8FC710\u4F4D";
    var publicSize20="\u957F\u5EA6\u4E0D\u8D85\u8FC720\u4F4D";
    var publicSize50="\u957F\u5EA6\u4E0D\u8D85\u8FC750\u4F4D";
    var publicSize64="\u957F\u5EA6\u4E0D\u8D85\u8FC764\u4F4D";
    var publicSize100="\u957F\u5EA6\u4E0D\u8D85\u8FC7100\u4F4D";
    var phoneError = "\u770B\u8D77\u6765\u4E0D\u50CF\u624B\u673A\u53F7\u5462";
    var publicNull = "\u4E0D\u80FD\u4E3A\u7A7A";
    var metertype = "{{ form.metertype.value }}"
    var protocol = "{{ form.protocol.value }}"
    var check_cycle = "{{ form.check_cycle.value }}"
    var dn = "{{ form.dn.value }}"
    var R = "{{ form.R.value }}"
    var q3 = "{{ form.q3.value }}"
    var metertype = "{{ form.metertype.value }}"
    var state = "{{ form.state.value }}"
    var coorType_old ="{{ form.coortype.value }}"
</script>
<script src="{% static 'virvo/wro/pressureEdit.js' %}"></script>