api/entm/urls.py
from django.urls import path,include
from django.conf.urls import url
from rest_framework.routers import DefaultRouter

from .organizations import views
from .users import views as user_views
from .roles import views as role_views

# Create a router and register our viewsets with it.
router = DefaultRouter()
# router.register(r'snippets', views.SnippetViewSet)
router.register(r'organ', views.OrganizationViewSet)
router.register(r'users', user_views.UserViewSet)
# router.register(r'user/login', user_views.UserLoginView)
# router.register(r'role', role_views.role_list,basename='role_list')

app_name='entm-api'
urlpatterns = [
    path('', include(router.urls)),

    url('user/login/',user_views.LoginView.as_view(),name='userlogin'),
    # path('', views.OrganizationListView.as_view()),
    # path('view/<pk>/', views.OrganizationViewSet.as_view({'get':'list','post':'create'}), name='organ-detail'),

    # roles
    url('role/list/',role_views.role_list,name='rolelist'),
    url('role/add/',role_views.role_add,name='roleadd'),
    url('role/edit/<int:pk>/',role_views.role_edit,name='roleedit'),
    url('role/delete_/<int:pk>/',role_views.role_delete,name='roledelete'),
    url('role/deletemore/',role_views.role_deletemore,name='roledeletemore'),
    url('role/choicePermissionTree/',role_views.choicePermissionTree,name='choicePermissionTree'),
    # url('role/add/',role_views.roleadd,name='roleadd'),
]


# for url in router.urls:
#     print(url,'\n')

api/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from api.entm.users.views import UserViewSet

from django.conf.urls import url
from django.contrib import admin

from .views import (
    OrganizationListAPIView,
    OrganizationDetailAPIView,
    MyRoleListAPIView,
    UserListAPIView,
    SimCardListAPIView,
    MeterListAPIView,
    StationListAPIView,
    StationDetailAPIView,
    VConcentratorListAPIView,
    VCommunityListAPIView,
    VPressureListAPIView,
    VPressureDetailAPIView,
    VSecondwaterListAPIView,
    VWatermeterListAPIView,
    VWatermeterDetailAPIView,
    WaterUserTypeListAPIView,
    MetercommListAPIView,
    MeterParameterListAPIView,
    MeterprotocolListAPIView,
    PersonalizedListAPIView,
)



router = routers.DefaultRouter()
router.register(r'users', UserViewSet)

app_name='api'
urlpatterns = [
    url(r'^', include(router.urls)),
    # url(r'^auth/', include('rest_auth.urls')),

    url(r'^personlized/list/$', PersonalizedListAPIView.as_view(), name='personlized'),
    url(r'^organizations/list/$', OrganizationListAPIView.as_view(), name='organlist'),
    url(r'^organizations/list/(?P<pk>\d+)/$', OrganizationDetailAPIView.as_view(), name='detail'),
    url(r'^role/list/$', MyRoleListAPIView.as_view(), name='myrolelist'),
    url(r'^user/list/$', UserListAPIView.as_view(), name='userlist'),
    url(r'^simcard/list/$', SimCardListAPIView.as_view(), name='simcardlist'),
    url(r'^meter/list/$', MeterListAPIView.as_view(), name='meterlist'),
    url(r'^station/list/$', StationListAPIView.as_view(), name='stationlist'),
    url(r'^station/list/(?P<pk>\d+)/$', StationDetailAPIView.as_view(), name='stationdetail'),
    url(r'^concentrator/list/$', VConcentratorListAPIView.as_view(), name='concentratorlist'),
    url(r'^community/list/$', VCommunityListAPIView.as_view(), name='communitylist'),
    url(r'^pressure/list/$', VPressureListAPIView.as_view(), name='pressurelist'),
    url(r'^pressure/list/(?P<pk>\d+)/$', VPressureDetailAPIView.as_view(), name='pressuredetail'),
    url(r'^secondwater/list/$', VSecondwaterListAPIView.as_view(), name='secondwaterlist'),
    url(r'^watermeter/list/$', VWatermeterListAPIView.as_view(), name='watermeterlist'),
    url(r'^watermeter/list/(?P<pk>\d+)/$', VWatermeterDetailAPIView.as_view(), name='watermeterdetail'),
    url(r'^waterusertype/list/$', WaterUserTypeListAPIView.as_view(), name='waterusertypelist'),

    url(r'^metercomm/list/$', MetercommListAPIView.as_view(), name='metercommlist'),
    url(r'^meterparameter/list/$', MeterParameterListAPIView.as_view(), name='meterparameterlist'),
    url(r'^meterprotocol/list/$', MeterprotocolListAPIView.as_view(), name='meterprotocollist'),
]

entm/api/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import url
from django.contrib import admin

from .views import (
    OrganizationListAPIView,
    MyRoleListAPIView,
    UserListAPIView,
    oranizationtree,
    # PostCreateAPIView,
    # PostDeleteAPIView,
    # PostDetailAPIView,
    # PostUpdateAPIView,
    )

app_name='entm-api'
urlpatterns = [
    url(r'^user/oranizationtree/$', OrganizationListAPIView.as_view(), name='organlist'),
    url(r'^organization/tree',oranizationtree,name='oranizationtree'),
    # url(r'^create/$', PostCreateAPIView.as_view(), name='create'),
    # url(r'^(?P<slug>[\w-]+)/$', PostDetailAPIView.as_view(), name='detail'),
    # url(r'^(?P<slug>[\w-]+)/edit/$', PostUpdateAPIView.as_view(), name='update'),
    # url(r'^(?P<slug>[\w-]+)/delete/$', PostDeleteAPIView.as_view(), name='delete'),

    url(r'^role/list/$', MyRoleListAPIView.as_view(), name='rolelist'),

    url(r'^user/list/$', UserListAPIView.as_view(), name='userlist'),
]

entm/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.utils.dateparse import parse_datetime,parse_date
from django.contrib.admin import widgets
from django.contrib.admin.widgets import AdminDateWidget,AdminSplitDateTime
from django.contrib.postgres.forms.ranges import DateRangeField, RangeWidget


import datetime
from core.models import Organization

# import settings


class OrganizationAddForm(forms.ModelForm):
    """docstring for OrganizationAddForm"""
    parent_attribute = forms.CharField()
    parent_organlevel = forms.CharField()

    class Meta:
        model = Organization
        fields = ('name','attribute','organlevel','register_date','owner_name','phone_number','firm_address','cid','pId',
            'coorType','zoomIn','longitude','latitude','islocation','location','province','city','district','adcode','districtlevel')

    def __init__(self,*args,**kwargs):
        print('form init',args,kwargs)
        super(OrganizationAddForm, self).__init__(*args, **kwargs)
        self.fields['register_date'].widget.attrs['input_formats'] =['%Y-%m-%d',]


    


class OrganizationEditForm(forms.ModelForm):
    """docstring for OrganizationEditForm"""

    parent_attribute = forms.CharField()
    parent_organlevel = forms.CharField()

    class Meta:
        model = Organization
        fields = ('name','attribute','organlevel','register_date','owner_name','phone_number','firm_address','cid','pId',
            'coorType','zoomIn','longitude','latitude','islocation','location','province','city','district','adcode','districtlevel')


    def __init__(self,*args,**kwargs):
        super(OrganizationEditForm, self).__init__(*args, **kwargs)
        if self.instance.parent:
            self.fields['parent_organlevel'].initial = self.instance.parent.organlevel
            self.fields['parent_attribute'].initial = self.instance.parent.attribute

    


class CsvImportForm(forms.Form):
    csv_file = forms.FileField()

       

api/entm/organizations/views.py
# -*- coding: utf-8 -*-
from rest_framework import generics 
from rest_framework import viewsets
from .serializers import OrganizationListSerializer, OrganizationDetailSerializer,OrganizationSerializer
from core.models import Organization

class OrganizationListView(generics.ListAPIView):
    """View For List All Published Organization"""

    queryset = Organization.objects.all()
    serializer_class = OrganizationListSerializer


class OrganizationDetailView(generics.RetrieveAPIView):
    """View For The Details Of A Single Organization"""

    queryset = Organization.objects.all()
    serializer_class = OrganizationDetailSerializer

class OrganizationViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows Organization to be viewed or edited.
    """
    queryset = Organization.objects.all()   #.order_by('-date_joined')
    serializer_class = OrganizationSerializer

api/entm/roles/views.py
# -*- coding: utf-8 -*-
from rest_framework import generics 
from rest_framework import status,viewsets
from .serializers import MyRolesListSerializer, MyRolesDetailSerializer,MyRolesSerializer
from accounts.models import MyRoles
from rest_framework.decorators import action,api_view
from rest_framework.response import Response

from django.http import HttpResponse,JsonResponse,HttpResponseRedirect,StreamingHttpResponse,Http404
import json
from core.menus import choicetreedict

from rest_framework.permissions import IsAdminUser,IsAuthenticated
from rest_framework import renderers
from rest_framework.mixins import (
    CreateModelMixin,
    ListModelMixin,
    RetrieveModelMixin,
    UpdateModelMixin,
    DestroyModelMixin
)


class MyRolesListView(generics.ListAPIView):
    """View For List All Published MyRoles"""

    queryset = MyRoles.objects.all()
    serializer_class = MyRolesListSerializer


class MyRolesDetailView(generics.RetrieveAPIView):
    """View For The Details Of A Single MyRoles"""

    queryset = MyRoles.objects.all()
    serializer_class = MyRolesDetailSerializer

class MyRolesViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows MyRoles to be viewed or edited.
    """
    queryset = MyRoles.objects.all()   #.order_by('-date_joined')
    serializer_class = MyRolesSerializer



def buildFrontbasetree2():
    ctree = []
    

    for key in choicetreedict.keys():
        pname = choicetreedict[key]["name"]
        pid = key
        

        tmp1 = {}
        tmp1["name"] = pname
        tmp1["pId"] = 0
        tmp1["id"] = pid
        # tmp1["checked"] = "true"    #nocheck
        tmp1["nocheck"] = "true"
        
        ctree.append(tmp1)
        
        submenu = choicetreedict[key]["submenu"][0]
        for sub_key in submenu.keys():
            name = submenu[sub_key]["name"]
            idstr = "{id}_{pid}".format(id=sub_key,pid=pid)
            cid = pid

            tmp2 = {}
            tmp2["name"] = name
            tmp2["pId"] = cid
            tmp2["id"] = idstr
            # tmp2["checked"] = "true"
            
            ctree.append(tmp2)

        

            

    return ctree    

@api_view(['GET','POST'])
def choicePermissionTree(request):
    user = request.user
    if not user.Role:
        if user.is_admin:
            return HttpResponse(json.dumps(buildFrontbasetree2())) 
    rid = user.Role.rid
    # rid = request.POST.get("roleId") or ''
    print(" get choicePermissionTree",rid)

    
    # print('buildtree:',buildtree)

    if len(rid) <= 0:
        user = request.user
        if user.is_admin:
            return HttpResponse(json.dumps(buildFrontbasetree2()))
        permissiontree = user.Role.permissionTree

    else:
        instance = MyRoles.objects.get(rid=rid)
        permissiontree = instance.permissionTree


    if len(permissiontree) > 0:
        ptree = json.loads(permissiontree)
        buildtree = buildFrontbasetree(request,ptree)
            


    return Response(result)

    return HttpResponse(json.dumps(buildtree))


class MyRoleViewSet(CreateModelMixin,
    ListModelMixin,
    RetrieveModelMixin,
    UpdateModelMixin,
    DestroyModelMixin,
    generics.GenericAPIView,
    viewsets.ViewSet):

    serializer_class = MyRolesSerializer
    queryset = MyRoles.objects.all()

    def list(self, request):
        draw = 1
        length = 0
        start=0
        print('role list')
        if request.method == "GET":
            draw = int(request.GET.get("draw", 1))
            length = int(request.GET.get("length", 10))
            start = int(request.GET.get("start", 0))
            pageSize = int(request.GET.get("pageSize", 10))
            search_value = request.GET.get("search[value]", None)
            simpleQueryParam = request.POST.get("simpleQueryParam")
            # order_column = request.GET.get("order[0][column]", None)[0]
            # order = request.GET.get("order[0][dir]", None)[0]

        if request.method == "POST":
            draw = int(request.POST.get("draw", 1))
            length = int(request.POST.get("length", 10))
            start = int(request.POST.get("start", 0))
            pageSize = int(request.POST.get("pageSize", 10))
            search_value = request.POST.get("search[value]", None)
            simpleQueryParam = request.POST.get("simpleQueryParam")
            # order_column = request.POST.get("order[0][column]", None)[0]
            # order = request.POST.get("order[0][dir]", None)[0]

        # print("get rolelist:",draw,length,start,search_value)
        current_user = request.user
        

        data = []
        # rolel = current_user.role_list()
        serializer = self.get_serializer(self.queryset,many=True)
        
        rolel = serializer.data
        recordsTotal = len(rolel)

        # def search_role(r):
        #     if simpleQueryParam in r.name:
        #         return True


        # if simpleQueryParam != "":
        #     print('simpleQueryParam:',simpleQueryParam)
        #     # userl = userl.filter(real_name__icontains=simpleQueryParam)
        #     rolel = [r for r in rolel if search_role(r) is True]

        # for r in rolel[start:start+length]:
        #     data.append({"idstr":r.rid,"name":r.name,"notes":r.notes})

        
        # recordsTotal = len(data) #rolel.count()

        result = dict()
        result["records"] = serializer.data
        result["draw"] = draw
        result["success"] = "true"
        result["pageSize"] = pageSize
        result["totalPages"] = recordsTotal/pageSize
        result["recordsTotal"] = recordsTotal
        result["recordsFiltered"] = recordsTotal
        result["start"] = 0
        result["end"] = 0
        
        return Response(result)

    def create(self, request, *args, **kwargs):
        print("create role")
        serializer = self.get_serializer(data=request.data)
        if serializer.is_valid(raise_exception=True):
            self.perform_create(serializer)
            # headers = self.get_success_headers(serializer.data)
            return Response(serializer.data, status=status.HTTP_201_CREATED, headers=headers)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def retrieve(self, request, pk=None):
        instance = self.get_object()
        serializer = self.get_serializer(instance)
        return Response(serializer.data)

    def update(self, request, pk=None,*args, **kwargs):
        partial = kwargs.pop('partial', False)
        instance = self.get_object()
        serializer = self.get_serializer(instance, data=request.data, partial=partial)
        serializer.is_valid(raise_exception=True)
        self.perform_update(serializer)

        if getattr(instance, '_prefetched_objects_cache', None):
            # If 'prefetch_related' has been applied to a queryset, we need to
            # forcibly invalidate the prefetch cache on the instance.
            instance._prefetched_objects_cache = {}

        return Response(serializer.data)

    def partial_update(self, request, pk=None):
        pass

    def destroy(self, request, pk=None):
        pass

    @action(detail=True, renderer_classes=[renderers.StaticHTMLRenderer])
    def deletemore(self,request, *args, **kwargs):
        
        ret = {"success":True}
        return Response(ret)

    def get_permissions(self):
        """
        Instantiates and returns the list of permissions that this view requires.
        """
        if self.action == 'list':
            permission_classes = [IsAuthenticated]
        else:
            permission_classes = [IsAdminUser]
        return [permission() for permission in permission_classes]

role_list = MyRoleViewSet.as_view({
    'get': 'list'
})

role_add = MyRoleViewSet.as_view({
    'post': 'create'
})

role_delete = MyRoleViewSet.as_view({
    'post': 'destroy'
})

role_edit = MyRoleViewSet.as_view({
    'post': 'update'
})

role_deletemore = MyRoleViewSet.as_view({
    'post': 'deletemore'
}, renderer_classes=[renderers.StaticHTMLRenderer])

templates/entm/assignrole.html
<form id="userRolesForm"
    role="form" action="{% url 'entm:roleList_' object.id %}" method="post" class="form-horizontal">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"
            aria-hidden="true">&times;</button>
        <h4 class="modal-title">分配角色 : {{ user.user_name }}</h4>
    </div>
    <div class="modal-body">
        <div class="row">
            <input name="userId" value="{{ object.id }}" type="hidden" /> 
            <input name="uid" value="{{ object.user_name }}" type="hidden" />
            <div class="col-xs-12">
                <ul class="widget-todo">
                    {% for r in role_list %}
                    
                    {% if user.Role == r %}
                    <li class="clearfix">
                        <label class="checkbox-outline"> 
                            <input type="checkbox"
                                name="name" disabled
                                id="{{ r.name }}" value="{{ r.id }}" />
                            <label readonly style="text-decoration: none;">{{ r.name }}</label>
                        </label> 
                     
                    </li>
                    {% else %}
                    
                    <li class="clearfix">
                        <label class="checkbox-outline"> 
                            <input type="checkbox" 
                                name="name" 
                                id="{{ r.name }}" value="{{ r.id }}" />
                            <label  style="text-decoration: none;" onclick = "checkValue(this)">{{ r.name }}</label>
                        </label> 
                     
                    </li>
                    {% endif %}

                    {% endfor %}

                    <!-- <li class="clearfix">
                        <label class="checkbox-outline"> 
                            <input type="checkbox"
                                name="roleNames" disabled
                                id="普通管理员" value="POWER_USER" />
                            <label readonly style="text-decoration: none;">普通管理员</label>
                        </label> 
                    </li>

                    <li class="clearfix">
                        <label class="checkbox-outline"> 
                            <input type="checkbox"
                                name="roleNames" id="一般管理员" value="ROLE_1e3bb126-b6d1-4670-9e51-5d5e8235f807" />
                            <label style="text-decoration: none;" onclick = "checkValue(this)">一般管理员</label>
                        </label> 
                        
                    </li> -->
                    
                </ul>
                <input id="roleIds" name="roleIds" type="hidden" />
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button id="doSubmitRoles" class="btn btn-primary" type="button">
            <strong>提 交</strong>
        </button>
        <button type="button" class="btn btn-default" data-dismiss="modal">
            <strong>关 闭</strong>
        </button>
    </div>
</form>
<script>
function checkValue(clickLable){
    var checkbox = $(clickLable).parent().find('input')[0];
    if (checkbox.checked == true) {
        checkbox.checked = false;
    }else {
        checkbox.checked = true;
    }
}


// the selector will match all input controls of type :checkbox
// and attach a click event handler 
// permit excluded choice select.
$("input:checkbox").on('click', function() {
  // in the handler, 'this' refers to the box clicked on
  var $box = $(this);
  if ($box.is(":checked")) {
    // the name of the box is retrieved using the .attr() method
    // as it is assumed and expected to be immutable
    var group = "input:checkbox[name='" + $box.attr("name") + "']";
    // the checked state of the group/box on the other hand will change
    // and the current value is retrieved using .prop() method
    $(group).prop("checked", false);
    $box.prop("checked", true);
  } else {
    $box.prop("checked", false);
  }
});


(function($,window){
    var Ids;
    var userRoles = {
        doSubmit: function(){
            var roleIds = [];
            $("input[name='name']:checked").each(function(index,item){
                var roleName = $(this).attr("value");
                roleIds.push(roleName);
             });
            if(roleIds.join(",") == Ids){
                $("#commonSmWin").modal("hide");//关闭弹窗
                return;
            }else{
                $("#roleIds").val(roleIds.join(","));
                console.log(roleIds);
//              $("#userRolesForm").submit();
                $("#userRolesForm").ajaxSubmit(function (data) {
                    if(typeof(data) == "object" &&
                        Object.prototype.toString.call(data).toLowerCase() == "[object object]" && !data.length){//如果后台返回的数据是json数据,则直接过去msg
                        layer.msg(data.msg,{move:false});
                    }else{
                        var dataset = eval(data);// $.parseJSON(data);//转为json对象
                        layer.msg(dataset.msg,{move:false});
                    }
                    $("#commonSmWin").modal("hide");//关闭弹窗
                    myTable.refresh();//刷新列表
                });
            }
        },
    }
  
    $(function(){
        myTable.add('commonSmWin', 'userRolesForm', null, null);
        $("#doSubmitRoles").on("click",userRoles.doSubmit);
        var startRoleIds = [];//窗体加载时多选框的值
        $("input[name='name']:checked").each(function(index,item){
            var roleName = $(this).attr("value");
            startRoleIds.push(roleName);
        });
        Ids = startRoleIds.join(",");
    })
})($,window)
</script>

templates/entm/assignstn.html
{% load staticfiles %}
<form id="vehiclePerForm"
    role="form" action="" method="post" class="form-horizontal">{% csrf_token %}
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"
            aria-hidden="true">&times;</button>
        <h4 class="modal-title"> 为用户 【 {{ user.user_name }} 】 授权站点</h4>
    </div>
    <div class="modal-body-per">
        <div class="row">
            <div class="col-md-12">
                <input type="hidden" id="id" name="id" value=""/> 
                <input id="vehicleTreeData" value="" type="hidden"/> 
                <input id="userVehicle" name="userVehicleList" type="hidden"/>
                
                <ul id="vehicleGroupDemo" name="fenceTree" class="ztree"></ul>          
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <!-- <div class="col-sm-7 col-md-7" style="text-align:left;margin-left:-17px;margin-top:-1px;">
                                                            <i class="info-isCompany"></i>&nbsp;&nbsp;:&nbsp;&nbsp;企业<br>
                                                            <i class="info-isGroup"></i>&nbsp;&nbsp;:&nbsp;&nbsp;分组，在分组管理中创建
                                                            </div> -->
    <!--    <div class="col-sm-5 col-md-5">     -->                                             
        <button id="doSubmitVehiclePer" class="btn btn-primary" type="button" disabled>
            <strong>提 交</strong>
        </button>
        <button type="button" style="margin-top:-1px;" class="btn btn-default" data-dismiss="modal">
            <strong>关 闭</strong>
        </button>
        <!-- </div>    -->
    </div>
</form>

{% comment %}
<script src="{% static 'virvo/wro/assignstn.js' %}"></script>
{% endcomment %}
<!-- <script src="/clbs/wro/userVehiclePer.js"></script> -->

templates/entm/csv_form.html
{% extends 'admin/base.html' %}

{% block content %}
    <div>
        <form action="." method="POST" enctype="multipart/form-data">
            {{ form.as_p }}
            {% csrf_token %}

                <button type="submit">Upload CSV</button>
        </form>
    </div>
    <br />

{% endblock %}

templates/entm/heroes_changelist.html
{% extends 'admin/change_list.html' %}

{% block object-tools %}
    <a href="import-csv/">Import CSV</a>
    <br />
    {{ block.super }}
{% endblock %}

templates/entm/importuser.html
{% load staticfiles %}
<form id="importForm" role="form" action="/entm/user/import" method="post"
    class="form-horizontal" enctype="multipart/form-data">{% csrf_token %}
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"
            aria-hidden="true">&times;</button>
        <h4 class="modal-title">导入用户</h4>
    </div>
    <div class="modal-body">
        <a class="btn btn-primary"  href="/entm/basetemp/download"><strong>下载模板</strong></a>
        <br/><br/>
        <div class="inpFilePhoto">
            <input type="file" id="excelPath" name="file" /><strong>导入文件</strong>
        </div>
        <div class="fileNameShow"></div>
        <div class="progress" style="display:none;">
          <div class="progress-bar progress-bar-progress" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
            0%
          </div>
        </div>
    </div>
    <div class="modal-footer modal-footer-martop">
        <button class="btn btn-primary" type="button" id="doSubmits">
            <strong>提 交</strong>
        </button>
        <button type="button" class="btn btn-default" id="close" data-dismiss="modal" >
            <strong>关 闭</strong>
        </button>
    </div>
</form>

{% block javascript %}
<script src="{% static 'virvo/resources/js/importFileV.js' %}"></script>
<script type="text/javascript">
$(function(){
    $("#close").click(function(){
        $("#importForm").hide();
    })
})
</script>
{% endblock %}

templates/entm/permission_error.html
    <div class="modal-header">
        <button type="button" id="doXEdit" class="close" data-dismiss="modal"
            aria-hidden="true">&times;</button>
        <h4 class="modal-title">{{ mheader }}</h4>
    </div>
    <div class="modal-body">
        {{ err_msg }}
    </div>
    <div class="modal-footer">
        <button id="doCloseEdit" type="button" class="btn btn-default" data-dismiss="modal">
            <strong>关 闭</strong>
        </button>
    </div>

templates/entm/roleedit.html
{% load staticfiles %}
<form id="editForm" role="form" action="{% url 'entm:roleedit' object.id %}" method="post" class="form-horizontal">{% csrf_token %}
    <div class="modal-header">
        <button type="button" id="doXEdit" class="close" data-dismiss="modal"
            aria-hidden="true">&times;</button>
        <h4 class="modal-title">修改角色</h4>
    </div>
    <div class="modal-body">
        <div class="row">
            <div class="col-md-12">
                <input id="idStr" type="text" hidden="true" name="id" value="{{ object.pk }}" />
                <input id="rolename" type="text" hidden="true" name="name" value="{{ object.name }}" />
                <div class="form-group">
                    <label class="col-md-3 control-label"><label
                        class="text-danger">*</label> 角色名称： </label>
                    <div class="col-md-7">
                        <input placeholder="请输入角色名称" type="text" readonly="true"
                            class="form-control" id="roleName" name="name" value="{{ form.name.value }}" />
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label">备注：</label>
                    <div class="col-md-7">
                        <textarea rows="4" class="form-control"
                            placeholder="最大140个字符" id="description" name="notes">{{ form.notes.value }}</textarea>
                    </div>
                </div>
                <input id="permissionEditTree" name="permissionTree" type="text"
                    hidden="true" />
                <div class="form-group">
                    <label class="col-md-3 control-label"> 操作权限：</label>
                    <div class="col-md-7">
                        <div class="treeArea">
                            <ul id="permissionEditDemo" name="fenceTree" class="ztree"></ul>
                        </div>
                    </div>
                </div>
                
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button id="doSubmitEdit" class="btn btn-primary" type="button">
            <strong>提 交</strong>
        </button>
        <button id="doCloseEdit" type="button" class="btn btn-default" data-dismiss="modal">
            <strong>关 闭</strong>
        </button>
    </div>
</form>
<script>
    var roleNameNull = "\u89D2\u8272\u540D\u79F0\u4E0D\u80FD\u4E3A\u7A7A";
    var publicSize20="\u957F\u5EA6\u4E0D\u8D85\u8FC720\u4F4D";
    var publicSize140="\u957F\u5EA6\u4E0D\u8D85\u8FC7140\u4F4D";
    var publicMinSize1Length="\u957F\u5EA6\u4E0D\u80FD\u5C0F\u4E8E1\u4F4D";
</script>
<script src="{% static 'virvo/wro/roleEdit.js' %}"></script>