api/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from api.entm.users.views import UserViewSet

from django.conf.urls import url
from django.contrib import admin

from .views import (
    OrganizationListAPIView,
    OrganizationDetailAPIView,
    MyRoleListAPIView,
    UserListAPIView,
    SimCardListAPIView,
    MeterListAPIView,
    StationListAPIView,
    StationDetailAPIView,
    VConcentratorListAPIView,
    VCommunityListAPIView,
    VPressureListAPIView,
    VPressureDetailAPIView,
    VSecondwaterListAPIView,
    VWatermeterListAPIView,
    VWatermeterDetailAPIView,
    WaterUserTypeListAPIView,
    MetercommListAPIView,
    MeterParameterListAPIView,
    MeterprotocolListAPIView,
    PersonalizedListAPIView,
)



router = routers.DefaultRouter()
router.register(r'users', UserViewSet)

app_name='api'
urlpatterns = [
    url(r'^', include(router.urls)),
    # url(r'^auth/', include('rest_auth.urls')),

    url(r'^personlized/list/$', PersonalizedListAPIView.as_view(), name='personlized'),
    url(r'^organizations/list/$', OrganizationListAPIView.as_view(), name='organlist'),
    url(r'^organizations/list/(?P<pk>\d+)/$', OrganizationDetailAPIView.as_view(), name='detail'),
    url(r'^role/list/$', MyRoleListAPIView.as_view(), name='myrolelist'),
    url(r'^user/list/$', UserListAPIView.as_view(), name='userlist'),
    url(r'^simcard/list/$', SimCardListAPIView.as_view(), name='simcardlist'),
    url(r'^meter/list/$', MeterListAPIView.as_view(), name='meterlist'),
    url(r'^station/list/$', StationListAPIView.as_view(), name='stationlist'),
    url(r'^station/list/(?P<pk>\d+)/$', StationDetailAPIView.as_view(), name='stationdetail'),
    url(r'^concentrator/list/$', VConcentratorListAPIView.as_view(), name='concentratorlist'),
    url(r'^community/list/$', VCommunityListAPIView.as_view(), name='communitylist'),
    url(r'^pressure/list/$', VPressureListAPIView.as_view(), name='pressurelist'),
    url(r'^pressure/list/(?P<pk>\d+)/$', VPressureDetailAPIView.as_view(), name='pressuredetail'),
    url(r'^secondwater/list/$', VSecondwaterListAPIView.as_view(), name='secondwaterlist'),
    url(r'^watermeter/list/$', VWatermeterListAPIView.as_view(), name='watermeterlist'),
    url(r'^watermeter/list/(?P<pk>\d+)/$', VWatermeterDetailAPIView.as_view(), name='watermeterdetail'),
    url(r'^waterusertype/list/$', WaterUserTypeListAPIView.as_view(), name='waterusertypelist'),

    url(r'^metercomm/list/$', MetercommListAPIView.as_view(), name='metercommlist'),
    url(r'^meterparameter/list/$', MeterParameterListAPIView.as_view(), name='meterparameterlist'),
    url(r'^meterprotocol/list/$', MeterprotocolListAPIView.as_view(), name='meterprotocollist'),
]

wirelessm/api/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import url
from django.contrib import admin

from .views import (
    WatermeterListAPIView,
    WQListAPIView,
    WAlarmListAPIView,
    showinfoStatics,
    getWatermeterMonth,
    getWatermeterdaily,
    neiborhooddailydata,
    neiborhoodmonthdata,
    getconcentratormaplist,
    getWatermeterflow,
    getWatermeterflow_data,
    getWatermeterdaily_data,
    getWatermeterMonth_data,
    readpercent,
    WStasticsListAPIView,
    wholedatastastics,
    funcdatastastics,
)

app_name='devm-api'
urlpatterns = [
    # url(r'^user/oranizationtree/$', OrganizationListAPIView.as_view(), name='organlist'),
    # url(r'^create/$', PostCreateAPIView.as_view(), name='create'),
    # url(r'^(?P<slug>[\w-]+)/$', PostDetailAPIView.as_view(), name='detail'),
    # url(r'^(?P<slug>[\w-]+)/edit/$', PostUpdateAPIView.as_view(), name='update'),
    # url(r'^(?P<slug>[\w-]+)/delete/$', PostDeleteAPIView.as_view(), name='delete'),

    url(r'^watermeter/list/$', WatermeterListAPIView.as_view(), name='watermeterlist'),

    # 超收率
    url(r'^watermeter/readpercent/$', readpercent, name='readpercent'),
    url(r'^watermeter/comunitiquery/$', WQListAPIView.as_view(), name='comunitiquery'),
    url(r'^watermeter/comunitiwateralarm/$', WAlarmListAPIView.as_view(), name='comunitiwateralarm'),
    url(r'^watermeter/showinfoStatics/',showinfoStatics,name='showinfoStatics'),
    url(r'^watermeter/getWatermeterflow/',getWatermeterflow,name='getWatermeterflow'),
    url(r'^watermeter/getWatermeterflow_data/',getWatermeterflow_data,name='getWatermeterflow_data'),
    url(r'^watermeter/getWatermeterdaily/',getWatermeterdaily,name='getWatermeterdaily'),
    url(r'^watermeter/getWatermeterdaily_data/',getWatermeterdaily_data,name='getWatermeterdaily_data'),
    url(r'^watermeter/getWatermeterMonth/',getWatermeterMonth,name='getWatermeterMonth'),
    url(r'^watermeter/getWatermeterMonth_data/',getWatermeterMonth_data,name='getWatermeterMonth_data'),
    # url(r'^community/list/$', CommunityListAPIView.as_view(), name='communitylist'),
    url(r'^neiborhooddailydata/?$', neiborhooddailydata, name='neiborhooddailydata'),#
    url(r'^neiborhoodmonthdata/?$', neiborhoodmonthdata, name='neiborhoodmonthdata'),#

    # url(r'^concentratormap/?$',views.ConcentratorMapView.as_view(),name='concentratormap'),
    url(r'^getconcentratormaplist/?$',getconcentratormaplist,name='getconcentratormaplist'),
    # url(r'^contentratordatastastic/?$',views.ContentratorDataStasticView.as_view(),name='contentratordatastastic'),
    url(r'^datastastics/?$',WStasticsListAPIView.as_view(),name="datastastics"),
    url(r'^wholedatastastics/?$',wholedatastastics,name="wholedatastastics"),
    url(r'^funcdatastastics/?$',funcdatastastics,name="funcdatastastics"),


]

wirelessm/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views
from django.views.generic import TemplateView

from . import views

app_name = 'wirelessm'
urlpatterns = [
    
    #使用hplus页面布局时的首页
    # url(r'^$', TemplateView.as_view(template_name='hplus.html'),name='virvo_home'),
    url(r'^$', TemplateView.as_view(template_name='_vbase.html'),name='virvo_home'),


    #无线抄表
    url(r'^concentratormap/?$',views.ConcentratorMapView.as_view(),name='concentratormap'),
    url(r'^getconcentratormaplist/?$',views.getconcentratormaplist,name='getconcentratormaplist'),
    url(r'^contentratordatastastic/?$',views.ContentratorDataStasticView.as_view(),name='contentratordatastastic'),
    url(r'^concentratorStatics/?$',views.concentratorStatics,name="concentratorStatics"),

    # 数据查询 
    url(r'^wlquerydata/?$',views.WlquerydataView.as_view(),name='wlquerydata'),
    url(r'^wlquerydata/showinfo/(?P<pk>[0-9]+)/?$',views.WlqueryShowInfoView.as_view(),name='wlqueryshowinfo'),
    url(r'^wlquerydata/showalarm/(?P<pk>[0-9]+)/?$',views.WlqueryShowAlarmView.as_view(),name='wlqueryshowalarm'),
    url(r'^watermeter/comunitiquery/',views.comunitiquery,name='comunitiquery'),
    url(r'^watermeter/showinfoStatics/',views.showinfoStatics,name='showinfoStatics'),
    url(r'^watermeter/getWatermeterdaily/',views.getWatermeterdaily,name='getWatermeterdaily'),
    url(r'^watermeter/getWatermeterMonth/',views.getWatermeterMonth,name='getWatermeterMonth'),
    url(r'^watermeter/exportbyselect',views.exportbyselect,name='exportbyselect'),
    
    # 小区日用水
    url(r'^neighborhoodusedayly/?$', views.NeighborhoodusedaylyView.as_view(), name='neighborhoodusedayly'),#
    url(r'^neiborhooddailydata/?$', views.neiborhooddailydata, name='neiborhooddailydata'),#
    
    # 小区月用水
    url(r'^neighborhoodusemonthly/$',views.NeighborhoodusemonthlyView.as_view(),name='neighborhoodusemonthly'),
    url(r'^neiborhoodmonthdata/?$', views.neiborhoodmonthdata, name='neiborhoodmonthdata'),#
    
    # 户表管理
    url(r'^neighborhoodmetermanager/?$',views.NeighborhoodmeterMangerView.as_view(),name='neighborhoodmetermanager'),
    # url(r'^watermeter/list/$',views.watermeterlist,name='watermeterlist'),
    url(r'^watermeter/add',views.WatermeterAddView.as_view(),name='watermeteradd'),
    url(r'^watermeter/edit/(?P<pk>\w+)/?$',views.WatermeterEditView.as_view(),name='watermeteredit'),
    url(r'^watermeter/delete/(?P<pk>[0-9]+)/?$',views.WatermeterDeleteView.as_view(),name='watermeterdelete'),
    url(r'^watermeter/deletemore',views.watermeterdeletemore,name='watermeterdeletemore'),
    url(r'^communitymeter/repetition/$',views.watermeter_repetition,name='watermeter_repetition'),
    url(r'^watermeter/export',views.watermeterexport,name='watermeterexport'),
    url(r'^watermeter/import',views.WatermeterImportView.as_view(),name='import'),
    url(r'^watermeter/download',views.watermeterdownload,name='watermeterdownload'),

    # 批量修改
    url(r'^watermeter/batchupdate',views.WatermeterBatchUpdateView.as_view(),name='batchupdate'),
    
]

wirelessm/models.py
from django.db import models

# Create your models here.

templates/wirelessm/batchupdatewatermeter.html
{% load staticfiles %}
<form id="importForm" role="form" action="/wirelessm/watermeter/batchupdate" method="post"
    class="form-horizontal" enctype="multipart/form-data">{% csrf_token %}
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"
            aria-hidden="true">&times;</button>
        <h4 class="modal-title">批量修改户表</h4>
    </div>
    <div class="modal-body">
        <a class="btn btn-primary"  href="/wirelessm/watermeter/download"><strong>下载模板</strong></a>
        <br/><br/>
        <div class="inpFilePhoto">
            <input type="file" id="excelPath" name="file" /><strong>导入文件</strong>
        </div>
        <div class="fileNameShow"></div>
        <div class="progress" style="display:none;">
          <div class="progress-bar progress-bar-progress" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
            0%
          </div>
        </div>
    </div>
    <!-- <input type="hidden" id="X-Progress-ID" name="X-Progress-ID" value=""/>

    <input type="hidden" id="id" name="id" value=""/> -->

    <div class="modal-footer modal-footer-martop">
        <button class="btn btn-primary" type="button" id="doSubmits">
            <strong>提 交</strong>
        </button>
        <button type="button" class="btn btn-default" id="close" data-dismiss="modal" >
            <strong>关 闭</strong>
        </button>
    </div>
</form>

{% block javascript %}
<script src="{% static 'virvo/resources/js/importFileV.js' %}"></script>
<script type="text/javascript">
$(function(){
    $("#close").click(function(){
        $("#importForm").hide();
    })
})
</script>
{% endblock %}

templates/wirelessm/importwatermeter.html
{% load staticfiles %}
<form id="importForm" role="form" action="/wirelessm/watermeter/import" method="post"
    class="form-horizontal" enctype="multipart/form-data">{% csrf_token %}
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"
            aria-hidden="true">&times;</button>
        <h4 class="modal-title">导入户表</h4>
    </div>
    <div class="modal-body">
        <a class="btn btn-primary"  href="/wirelessm/watermeter/download"><strong>下载模板</strong></a>
        <br/><br/>
        <div class="inpFilePhoto">
            <input type="file" id="excelPath" name="file" /><strong>导入文件</strong>
        </div>
        <div class="fileNameShow"></div>
        <div class="progress" style="display:none;">
          <div class="progress-bar progress-bar-progress" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
            0%
          </div>
        </div>
    </div>
    <!-- <input type="hidden" id="X-Progress-ID" name="X-Progress-ID" value=""/>

    <input type="hidden" id="id" name="id" value=""/> -->

    <div class="modal-footer modal-footer-martop">
        <button class="btn btn-primary" type="button" id="doSubmits">
            <strong>提 交</strong>
        </button>
        <button type="button" class="btn btn-default" id="close" data-dismiss="modal" >
            <strong>关 闭</strong>
        </button>
    </div>
</form>

{% block javascript %}
<script src="{% static 'virvo/resources/js/importFileV.js' %}"></script>
<script type="text/javascript">
$(function(){
    $("#close").click(function(){
        $("#importForm").hide();
    })
})
</script>
{% endblock %}

templates/wirelessm/watermeteradd.html
{% load staticfiles %}
<form id="addForm" role="form" action="{% url 'wirelessm:watermeteradd' %}" method="post" class="form-horizontal">{% csrf_token %}
    <div class="modal-header">
        <button type="button" id="doXAdd" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">新增水表</h4>
    </div>
    <div class="modal-body">
        <input  type="text" class="hidden" id="cid" name="cid" value="{{ cid }}" />
        <input  type="text" class="hidden" id="pid" name="pId" value="{{ pId }}"/>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label class="col-md-2 control-label" style="padding-right: 0px;"><label class="text-danger">*</label> 用户代码(收费编号)：</label>
                    <div class="col-md-4">
                        <input name="numbersth" placeholder="请输入户号" type="text" maxlength="50" class="form-control" id="numbersth"/>
                        <label id="numbersth-error" style="display: none" class="error" for="numbersth">请输入用户代码(收费编号)</label>
                    </div>
                    <label class="col-md-2 control-label" style="padding-right: 0px;"><label class="text-danger">*</label> 楼号：</label>
                    <div class="col-md-4">
                        <input name="buildingname" placeholder="请输入栋号" type="text" maxlength="50" class="form-control" id="buildingname"/>
                        <label id="buildingname-error" style="display: none" class="error" for="buildingname">请输入楼号</label>
                    </div>
                    <!-- <label class="col-md-2 control-label"><label class="text-danger">*</label> 所属组织：</label>
                    <div class="has-feedback col-md-4">
                        <input name="belongto" class="form-control" id="zTreeOrganSel"
                            placeholder="请选择所属企业" readonly="readonly" style="background-color: #fafafa; cursor: pointer;"  type="text"/>
                        <span class="fa fa-chevron-down form-control-feedback" aria-hidden="true" id="zTreeCitySelSpan"></span>
                        <div class="ztreeModelBox" id="zTreeContent">
                            <ul id="ztreeDemo" class="ztree"></ul>
                        </div>
                        <input id = "groupId" name = "groupId" type="text" hidden="true" />
                        <label id="error_label_add" class="error" style="display: none;"></label>
                    </div> -->
                </div>
                <div class="form-group">
                    <label class="col-md-2 control-label" style="padding-right: 0px;"><label class="text-danger">*</label> 单元号、房号：</label>
                    <div class="col-md-4">
                        <input name="roomname" placeholder="请输入房号" type="text" maxlength="50" class="form-control" id="roomname"/>
                        <label id="roomname-error" style="display: none" class="error" for="roomname">请输入单元号、房号</label>
                    </div>
                    <label class="col-md-2 control-label"><label class="text-danger">*</label>所属小区：</label>
                    <div class="col-md-4">
                        <div class="input-group">
                            <input name="communityid" type="hidden" class="form-control" id="communityid">
                            <input name="communitysel" type="text" class="form-control" id="communitysel">
                            <div class="input-group-btn">
                                <button type="button" class="btn btn-white dropdown-toggle"
                                    data-toggle="dropdown">
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu dropdown-menu-right" role="menu">
                                </ul>
                            </div>
                        </div>
                    </div>


                </div>

                <div class="form-group">
                    <label class="col-md-2 control-label" style="padding-right: 0px;"><label class="text-danger">*</label> 表编号(水表表身编码)：</label>
                    <div class="col-md-4">
                        <input name="serialnumber" placeholder="请输入编号" type="text" maxlength="50" class="form-control" id="serialnumber"/>
                        <label id="serialnumber-error" style="display: none" class="error" for="serialnumber">请输入编号</label>
                    </div>
                    <label class="col-md-2 control-label">所属集中器：</label>
                    <div class="col-md-4">
                        <input name="concentrator" type="text" class="form-control" id="concentrator" readonly="true">
                        <!-- <div class="input-group">
                            <input name="concentrator" type="text" class="form-control" id="concentrator">
                            <div class="input-group-btn">
                                <button type="button" class="btn btn-white dropdown-toggle"
                                    data-toggle="dropdown">
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu dropdown-menu-right" role="menu">
                                </ul>
                            </div>
                        </div> -->
                    </div>


                </div>
                <div class="form-group">
                    <label class="col-md-2 control-label" style="padding-right: 0px;"> 用户姓名：</label>
                    <div class="col-md-4">
                        <input name="username" placeholder="请输入用户姓名" type="text" maxlength="50" class="form-control" id="username"/>
                        
                    </div>
                    <label class="col-md-2 control-label" style="padding-right: 0px;">用户电话：</label>
                    <div class="col-md-4">
                        <input name="usertel" placeholder="用户电话" type="text" maxlength="50" class="form-control" id="usertel"/>
                        
                    </div>
                    
                </div>
                <div class="form-group">
                    <label class="col-md-2 control-label" style="padding-right: 0px;"> 口径：</label>
                    <div class="col-md-4">
                        <select name="dn" id="dn" autocomplete="off"  class="form-control">
                            <option  value="15">15</option>
                            <option  value="20">20</option>
                            <option  value="25">25</option>
                            
                        </select>
                    </div>
                    <label class="col-md-2 control-label" style="padding-right: 0px;"> 厂家：</label>
                    <div class="col-md-4">
                        <input name="manufacturer" placeholder="请输入厂家" type="text" maxlength="50" class="form-control" id="manufacturer"/>
                        
                    </div>
                    
                </div>
                <div class="form-group">
                    <label class="col-md-2 control-label" style="padding-right: 0px;"> 用户地址：</label>
                    <div class="col-md-4">
                        <input name="useraddr" placeholder="请输入用户地址" type="text" maxlength="150" class="form-control" id="useraddr"/>
                        
                    </div>
                    <label class="col-md-2 control-label" style="padding-right: 0px;">安装位置：</label>
                    <div class="col-md-4">
                        <input name="installationsite" placeholder="安装位置" type="text" maxlength="150" class="form-control" id="installationsite"/>
                        
                    </div>
                    
                </div>
                <div class="form-group">
                    <label class="col-md-2 control-label" style="padding-right: 0px;">阀控表：</label>
                    <div class="col-md-4">
                        <select name="metercontrol" id="metercontrol" autocomplete="off"  class="form-control">
                            <!-- <option  value="">- 请选择类型 -</option> -->
                            <option value="0">非阀控表</option>
                            <option value="1">阀控表</option>
                            
                        </select>
                        
                    </div>
                    <label class="col-md-2 control-label" style="padding-right: 0px;"> 生产日期：</label>
                    <div class="col-md-4">
                        <input style="cursor: pointer;  background-color: #fafafa;" class="form-control layer-date laydate-icon"
                               id="madedate" name="madedate" placeholder=""/>
                    </div>
                    
                </div>
                <div class="form-group">
                    <label class="col-md-2 control-label" style="padding-right: 0px;"><label class="text-danger">*</label>表类型：</label>
                    <div class="col-md-4">
                        <select name="metertype" id="metertype" autocomplete="off"  class="form-control">
                            <!-- <option  value="">- 请选择类型 -</option> -->
                            <option value="0">NB物联</option>
                            <option value="1">LORA智能</option>
                            <option value="2">有线远传</option>
                            <option value="3">其他</option>
                            
                        </select>
                        
                    </div>
                    <label class="col-md-2 control-label" style="padding-right: 0px;">关联IMEI：</label>
                    <div class="col-sm-4 col-md-4 form-group" style="padding-top:10px; margin:0px;">
                        <div style="position:relative;">
                            <span style="overflow:hidden;">
                                <input type="hidden" id="wateraddr" name="wateraddr" />
                                </span>
                                <div class="input-group">
                                    <input value=""  type="text" placeholder="" class="form-control" maxlength="20" id="sims" name="simid">
                                    
                                    <div class="input-group-btn">
                                        <!-- <input type="hidden" class="hidenSubmitControl"/> -->
                                      <button type="button" id="button" class="btn btn-white dropdown-toggle disabled loading-state-button" data-toggle="dropdown">
                                          <i class="fa fa-spinner loading-state"></i>
                                      </button>
                                      <ul class="dropdown-menu dropdown-menu-right" role="menu"  style="width:100%">
                                      </ul>
                                    </div>
                                </div>
                        </div>
                    </div>
                    
                    
                </div>
                
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button id="doSubmit"  class="btn btn-primary" type="button">
            <strong>提 交</strong>
        </button>
        <button id="doCloseAdd" type="button" class="btn btn-default" data-dismiss="modal">
            <strong>关 闭</strong>
        </button>
    </div>
    <input  type="hidden" value="ef6c759b-ef14-46f7-bec1-5819d0c322fa" name="avoidRepeatSubmitToken" id="avoidRepeatSubmitToken">
</form>
<!-- <script type="text/javascript" src="/clbs/resources/js/sendAjax.js"></script> -->
<script src="{% static 'virvo/resources/js/sendAjax.js' %}"></script>

<script>
var deviceNumberNull = "\u7EC8\u7AEF\u53F7\u4E0D\u80FD\u4E3A\u7A7A";
    var deviceNumberError = "\u8BF7\u8F93\u5165\u5B57\u6BCD/\u6570\u5B57/\u4E0B\u5212\u7EBF/\u77ED\u6760\uFF0C\u8303\u56F4\uFF08\u8F66\uFF097~15\uFF08\u4EBA\uFF091~20";
    var deviceNumberExists = "\u7EC8\u7AEF\u53F7\u5DF2\u5B58\u5728";
    var deviceTypeNull="\u901A\u8BAF\u7C7B\u578B\u4E0D\u80FD\u4E3A\u7A7A";

    var publicSize6="\u957F\u5EA6\u4E0D\u8D85\u8FC76\u4F4D";
    var publicSize10="\u957F\u5EA6\u4E0D\u8D85\u8FC710\u4F4D";
    var publicSize20="\u957F\u5EA6\u4E0D\u8D85\u8FC720\u4F4D";
    var publicSize50="\u957F\u5EA6\u4E0D\u8D85\u8FC750\u4F4D";
    var publicSize64="\u957F\u5EA6\u4E0D\u8D85\u8FC764\u4F4D";
    var publicSize100="\u957F\u5EA6\u4E0D\u8D85\u8FC7100\u4F4D";
    var phoneError = "\u770B\u8D77\u6765\u4E0D\u50CF\u624B\u673A\u53F7\u5462";
    var publicNull = "\u4E0D\u80FD\u4E3A\u7A7A";

    laydate.render({elem: '#madedate',theme: '#6dcff6'});
</script>

<script src="{% static 'virvo/wro/watermeterAdd.js' %}"></script>